source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


api_url = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include(api_url)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from webapp.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    ClientGroupUpdateView, ClientDeletedListView, ClientRestoreView,\
    PaymentCreateView,  PaymentUpdateView, PaymentDeleteView, \
    CoachListView, CoachDetailView, CoachCreateView, CoachUpdateView, CoachDeleteView, CoachStatisticsView,\
    GroupListView, GroupDetailView, GroupCreateView, GroupUpdateView, GroupDeleteView, \
    GroupClientUpdateView, GroupClientDeleteView, \
    TrainingListView, TrainingCreateView, TrainingDeleteView, \
    SendInvite, Mailing, GroupMailing


app_name = 'webapp'

client_url = [
    path('', ClientListView.as_view(), name='index'),
    path('deleted/list', ClientDeletedListView.as_view(), name='deleted_list'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('<int:pk>/client/restore', ClientRestoreView.as_view(), name='client_restore'),
    path('<int:pk>/client/update', ClientGroupUpdateView.as_view(), name='client_group_update'),
]

payment_url = [
    path('<int:pk>/create/', PaymentCreateView.as_view(), name='payment_create'),
    path('<int:pk>/update/', PaymentUpdateView.as_view(), name='payment_update'),
    path('<int:pk>/delete/', PaymentDeleteView.as_view(), name='payment_delete'),
]

coach_url = [
    path('list/', CoachListView.as_view(), name='coach_list'),
    path('<int:pk>/detail/', CoachDetailView.as_view(), name='coach_detail'),
    path('create/', CoachCreateView.as_view(), name='coach_create'),
    path('<int:pk>/update/', CoachUpdateView.as_view(), name='coach_update'),
    path('<int:pk>/delete/', CoachDeleteView.as_view(), name='coach_delete'),
    path('statistics/', CoachStatisticsView.as_view(), name='coach_statistics'),

]

group_url = [
    path('list/', GroupListView.as_view(), name='group_list'),
    path('<int:pk>/detail/', GroupDetailView.as_view(), name='group_detail'),
    path('create/', GroupCreateView.as_view(), name='group_create'),
    path('<int:pk>/update/', GroupUpdateView.as_view(), name='group_update'),
    path('<int:pk>/delete/', GroupDeleteView.as_view(), name='group_delete'),
    path('<int:pk>/client/update', GroupClientUpdateView.as_view(), name='group_client_update'),
    path('<int:pk>/client/delete', GroupClientDeleteView.as_view(), name='group_client_delete'),
]


training_url = [
    path('<int:pk>/list/', TrainingListView.as_view(), name='training_list'),
    path('<int:pk>/create/', TrainingCreateView.as_view(), name='training_create'),
    path('<int:pk>/delete/', TrainingDeleteView.as_view(), name='training_delete'),
]

send_invitee_massage_url = [
    path('<int:pk>/invite/', SendInvite.as_view(), name='send_invite'),
    path('<int:pk>/group/', GroupMailing.as_view(), name='send_group_mailing'),
    path('mailing/', Mailing.as_view(), name='mailing_page'),
]

urlpatterns = [
    path('', include(client_url)),
    path('client/', include(client_url)),
    path('payment/', include(payment_url)),
    path('coach/', include(coach_url)),
    path('group/', include(group_url)),
    path('training/', include(training_url)),
    path('send/', include(send_invitee_massage_url))
]

source/webapp/views/client_views.py
from django.core.exceptions import BadRequest
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.utils.http import urlencode
from django.urls import reverse, reverse_lazy
from django.db.models import Count, QuerySet
from webapp.models import Client
from webapp.forms import ClientForm, AddGroupClient, SearchForm
from webapp.filters import ClientFilter
from django.db.models import Q
from typing import Optional, Union


class ClientListView(ListView):
    model = Client
    template_name: str = 'clients/clients_list.html'
    context_object_name: str = 'clients'
    paginate_by: int = 10

    def get_search_form(self) -> SearchForm:
        return SearchForm(self.request.GET)

    def get_search_value(self) -> Optional[str]:
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get(self, request, *args, **kwargs) -> Union[redirect, ListView]:
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.filter(is_active=True).annotate(visit_count=Count('trainings'))
        if self.search_value:
            queryset = queryset.filter(
                Q(telegram_name__icontains=self.search_value) | Q(phone__icontains=self.search_value))
        return ClientFilter(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['filter'] = ClientFilter(self.request.GET, queryset=self.get_queryset())
        context['form'] = self.form
        if self.request.GET.get('is_paid'):
            context['query'] = urlencode({'is_paid': self.request.GET.get('is_paid')})
        elif self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ClientCreateView(CreateView):
    model = Client
    form_class: ClientForm = ClientForm
    template_name: str = 'clients/client_create.html'

    def get_success_url(self) -> str:
        return reverse('webapp:client_detail', kwargs={'pk': self.object.pk})


class ClientDetailView(DetailView):
    model = Client
    template_name: str = 'clients/client_detail.html'

    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.filter(is_active=True).annotate(visit_count=Count('trainings'))
        return queryset

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        client = self.get_object()
        payments = client.payments.order_by('-paid_at')
        paginator = Paginator(payments, 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        is_active = Client.objects.active_clients().filter(pk=client.pk)
        context['form'] = AddGroupClient() if is_active and client.group is None else None
        context['page_obj'] = page_obj
        context['is_paginated'] = page_obj.has_other_pages()
        context['payments'] = page_obj.object_list
        return context


class ClientUpdateView(UpdateView):
    template_name = 'clients/client_update.html'
    model = Client
    form_class = ClientForm

    def get_success_url(self) -> str:
        return reverse('webapp:client_detail', kwargs={'pk': self.object.pk})


class ClientDeleteView(DeleteView):
    template_name: str = 'clients/client_delete.html'
    model = Client
    context_object_name: str = 'client'
    success_url: str = reverse_lazy('webapp:index')

    def post(self, request, *args, **kwargs):
        client = get_object_or_404(Client, pk=int(kwargs.get('pk')))
        client.is_active = False
        client.group = None
        client.save()
        return redirect(self.success_url)


class ClientRestoreView(DeleteView):
    template_name: str = 'clients/client_restore.html'
    model = Client
    context_object_name: str = 'client'
    success_url: str = reverse_lazy('webapp:deleted_list')

    def post(self, request, *args, **kwargs):
        client = get_object_or_404(Client, pk=int(kwargs.get('pk')))
        client.is_active = True
        client.save()
        return redirect(self.success_url)


class ClientDeletedListView(ListView):
    model = Client
    template_name: str = 'clients/clients_deleted_list.html'
    context_object_name: str = 'clients'
    paginate_by: int = 10

    def get_search_form(self) -> SearchForm:
        return SearchForm(self.request.GET)

    def get_search_value(self) -> Optional[str]:
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get(self, request, *args, **kwargs) -> Union[redirect, ListView]:
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.filter(is_active=False).annotate(visit_count=Count('trainings'))
        if self.search_value:
            queryset = queryset.filter(
                Q(telegram_name__icontains=self.search_value) | Q(phone__icontains=self.search_value))
        return ClientFilter(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['filter'] = ClientFilter(self.request.GET, queryset=self.get_queryset())
        context['form'] = self.form
        if self.request.GET.get('is_paid'):
            context['query'] = urlencode({'is_paid': self.request.GET.get('is_paid')})
        elif self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ClientGroupUpdateView(View):
    def post(self, request, *args, **kwargs) -> HttpResponse:
        client_pk: int = kwargs.get('pk')
        group_id: int = int(request.POST.get('group_id'))
        is_active: bool = Client.objects.active_clients().filter(pk=client_pk)
        client: Client = get_object_or_404(Client, pk=client_pk)
        if is_active and client.group is None:
            client.group_id = group_id
            client.save()
            return redirect(self.get_redirect_url(group_id))
        raise BadRequest('Клиент неактивен или уже состоит в группе')

    def get_redirect_url(self, group_pk: int) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': group_pk})

source/webapp/views/coach_views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.db.models import Count, QuerySet
from webapp.models import Coach
from webapp.forms import CoachForm, CoachStatisticsPeriodForm


class CoachListView(ListView):
    model = Coach
    template_name: str = 'coaches/coach_list.html'
    context_object_name: str = 'coaches'
    paginate_by: int = 10


class CoachDetailView(DetailView):
    model = Coach
    template_name: str = 'coaches/coach_detail.html'
    context_object_name: str = 'coach'

    def get_context_data(self, **kwargs) -> dict:
        groups = self.get_object().groups.filter(is_active=True).all()
        return super().get_context_data(groups=groups, **kwargs)


class CoachCreateView(CreateView):
    model = Coach
    template_name: str = 'coaches/coach_create.html'
    form_class = CoachForm

    def get_success_url(self) -> str:
        return reverse('webapp:coach_detail', kwargs={'pk': self.object.pk})


class CoachUpdateView(UpdateView):
    model = Coach
    template_name: str = 'coaches/coach_update.html'
    form_class = CoachForm

    def get_success_url(self) -> str:
        return reverse('webapp:coach_detail', kwargs={'pk': self.object.pk})


class CoachDeleteView(DeleteView):
    model = Coach
    template_name: str = 'coaches/coach_delete.html'
    context_object_name: str = 'coach'
    success_url: str = reverse_lazy('webapp:coach_list')


class CoachStatisticsView(ListView):
    model = Coach
    template_name: str = 'coaches/coach_statistics.html'
    context_object_name: str = 'coaches'
    paginate_by: int = 10

    def get_queryset(self) -> QuerySet:
        start_date = self.request.GET.get('start_date')
        end_date = self.request.GET.get('end_date')
        coaches = super().get_queryset()
        if start_date and end_date:
            coaches = coaches.filter(
                    coach_trainings__created_at__gte=start_date, coach_trainings__created_at__lte=end_date
                )
        queryset = coaches.annotate(quantity=Count('coach_trainings')).order_by('telegram_name')
        return queryset

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['form'] = CoachStatisticsPeriodForm(self.request.GET)
        return context

source/webapp/views/groups_views.py
from django.http import HttpRequest
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, View
from webapp.models import Group, Client
from webapp.forms import GroupForm
from django.urls import reverse, reverse_lazy
from webapp.forms import AddClientGroup


class GroupListView(ListView):
    model = Group
    template_name: str = 'groups/group_list.html'
    context_object_name: str = 'groups'
    paginate_by: int = 5

    def get_queryset(self):
        return Group.objects.filter(is_active=True)


class GroupDetailView(DetailView):
    model = Group
    template_name: str = 'groups/group_detail.html'

    def get_context_data(self, **kwargs) -> dict:
        clients = self.get_object().clients.filter(is_active=True).all()
        clients_in_group = True if self.get_object().clients.active_clients().filter(is_active=True, group__isnull=True) else False
        form = AddClientGroup()
        return super().get_context_data(clients=clients, form=form, clients_in_group=clients_in_group, **kwargs)


class GroupCreateView(CreateView):
    model = Group
    form_class = GroupForm
    template_name: str = 'groups/group_create.html'

    def get_success_url(self) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': self.object.pk})


class GroupUpdateView(UpdateView):
    model = Group
    template_name: str = 'groups/group_update.html'
    form_class = GroupForm

    def get_success_url(self) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': self.object.pk})


class GroupDeleteView(DeleteView):
    model = Group
    template_name: str = 'groups/group_delete.html'
    context_object_name: str = 'group'
    success_url: str = reverse_lazy('webapp:group_list')

    def post(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=int(kwargs.get('pk')))
        group.is_active = False
        clients = Client.objects.all().filter(group__id=group.pk)
        for client in clients:
            client.group = None
            client.save()

        group.save()
        return redirect(self.success_url)


class GroupClientUpdateView(View):
    def post(self, request, *args, **kwargs):
        group_pk = kwargs.get('pk')
        client_ids = request.POST.getlist('active_client_id')
        for client_id in client_ids:
            client = get_object_or_404(Client, pk=int(client_id))
            client.group_id = group_pk
            client.save()
        return redirect(self.get_redirect_url(group_pk))

    def get_redirect_url(self, group_pk: int) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': group_pk})


class GroupClientDeleteView(View):
    def get(self, request: HttpRequest, *args: tuple, **kwargs: dict):
        client_id = kwargs.get('pk')
        client = get_object_or_404(Client, pk=client_id)
        group_pk = client.group_id
        client.group_id = None
        client.save()
        return redirect(self.get_redirect_url(group_pk))

    def get_redirect_url(self, group_pk) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': group_pk})

source/webapp/views/trainings_views.py
from django.http import HttpRequest
from django.views.generic import DetailView, View, DeleteView
from webapp.models import Training, Client
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic.list import MultipleObjectMixin


class TrainingListView(DetailView, MultipleObjectMixin):
    model = Client
    template_name: str = 'trainings/training_list.html'
    paginate_by: int = 8

    def get_context_data(self, **kwargs) -> dict:
        client = get_object_or_404(Client, pk=self.kwargs.get('pk'))
        object_list = client.trainings.all()
        context = super(TrainingListView, self).get_context_data(object_list=object_list)
        return context


class TrainingCreateView(View):
    def post(self, request: HttpRequest, *args: tuple, **kwargs: dict):
        client = get_object_or_404(Client, pk=self.kwargs.get('pk'))
        if client in Client.objects.active_clients():
            training = Training.objects.create(client=client, group=client.group)
            training.save()
        return redirect('webapp:client_detail', client.pk)


class TrainingDeleteView(DeleteView):
    model = Training
    template_name: str = 'trainings/training_delete.html'
    context_object_name: str = 'training'

    def get_success_url(self) -> str:
        return reverse('webapp:training_list', kwargs={'pk': self.object.client.pk})

source/webapp/templates/coaches/coach_create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Внести информацию о тренере</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Добавить" %}
    </form>
{% endblock %}

source/webapp/templates/coaches/coach_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="text-center fs-1 m-3 p-3">Вы действительно хотите удалить тренера {{ coach.first_name }}?</h1>
    <form method="POST" action="{% url 'webapp:coach_delete' coach.pk %}" class="text-center">
        {% csrf_token %}
        <button type="submit" class="sbmt_btn">Да</button>
        <a class="sbmt_btn" href="{% url 'webapp:coach_detail' coach.pk%}" role="button">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/coaches/coach_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
   <div class="card m-5">
        <div class="row no-gutters">
            <div class="col-md-4">
              {% if coach.photo %}
                <div class="col-md-16">
                    <img src="{{ coach.photo.url }}" class="card-img">
                </div>
              {% else %}
                <div class="col-md-16">
                    <img src="{% static "images/no_photo.jpg" %}" class="card-img">
                </div>
              {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title d-flex align-items-center">
                            Имя: {{ coach.first_name }}
                            <p class="card-text ml-auto">
                                <a href="{% url 'webapp:coach_update' coach.pk %}" class="cng_btn"><i class="bi bi-pencil"></i></a>
                                <a href="{% url 'webapp:coach_delete' coach.pk %}" class="cng_btn ml-3"><i class="bi bi-trash3-fill"></i></a>
                            </p>

                    </h4>
                    <div class="ms-auto">

                    </div>
                    {% if not client.last_name %}
                        <p class="card-text">Фамилия: --</p>
                    {% else %}
                        <p class="card-text">Фамилия: {{ client.last_name }}</p>
                    {% endif %}
                    <p class="card-text">Группы:
                        {% for group in groups %}
                            <a href="{% url 'webapp:group_detail' group.id %}">{{ group.name }}</a>{% if  not forloop.last %},{% endif %}
                        {% endfor %}
                    </p>

                    <p class="card-text">Telegram: {{ coach.telegram_name }}</p>
                    {% if not coach.email %}
                        <p class="card-text">Почта: --</p>
                    {% else %}
                        <p class="card-text">Почта: {{ coach.email }}</p>
                    {% endif %}
                    {% if not coach.phone %}
                        <p class="card-text">Телефон: --</p>
                    {% else %}
                        <p class="card-text">Телефон: {{ coach.phone }}</p>
                    {% endif %}
                    {% if not coach.description %}
                        <p class="card-text">Комментарий: --</p>
                    {% else %}
                        <p class="card-text">Комментарий: {{ coach.description }}</p>
                    {% endif %}
                     <p class="card-text">Приступил к работе: {{ coach.started_to_work|date:"d M Y" }}</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

source/webapp/templates/coaches/coach_list.html
{% extends 'base.html' %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'webapp:coach_create' %}">
            Добавить тренера(+)
        </a>
    </li>
    <li>
        <a class="nav-link active" aria-current="page" href="{% url 'webapp:coach_statistics' %}">
            Статистика тренеров
        </a>
    </li>

{% endblock %}

{% block content %}
    <h2 class="card-title text-center m-3 p-3">Список тренеров</h2>
     <table class="table w-100 table-striped" style="table-layout: auto;">
        <thead>
        <tr>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
            <th scope="col">Telegram</th>
            <th scope="col">Номер</th>
            <th scope="col">Количество занятий</th>
            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>

        {% for coach in coaches %}
            <tr>
                <td><a href="{% url 'webapp:coach_detail' coach.pk %}">{{ coach.first_name }}</a></td>
                {% if coach.last_name %}
                    <td>{{ coach.last_name }}</td>
                {% else %}
                    <td>--</td>
                {% endif %}
                <td>{{ coach.telegram_name }}</td>
                {% if coach.phone %}
                    <td>{{ coach.phone }}</td>
                {% else %}
                    <td>--</td>
                {% endif %}
                {% if coach.quantity %}
                    <td>{{ coach.quantity }}</td>
                {% else %}
                    <td>0</td>
                {% endif %}
                <td><a href="{% url 'webapp:coach_update' coach.pk %}"><i class="bi bi-pencil m-4"></i></a>
                <a href="{% url 'webapp:coach_delete' coach.pk %}"><i class="bi bi-trash3-fill m-3"></i></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
    {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/coaches/coach_statistics.html
{% extends 'base.html' %}
{% block nav %}
{% endblock %}

{% block content %}
    <h2 class="card-title text-center m-3 p-3">Список тренеров</h2>

    <form class="mb-3" action="" method="GET">
        {% include 'partial/form.html' with button_text="Применить" %}
    </form>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
            <th scope="col">Telegram</th>
            <th scope="col">Номер</th>
            <th scope="col">Приступил к работе</th>
            <th scope="col">Количество занятий</th>
        </tr>
        </thead>
        <tbody>

        {% for coach in coaches %}
            <tr>
                <td><a href="{% url 'webapp:coach_detail' coach.pk %}">{{ coach.first_name }}</a></td>
                {% if coach.last_name %}
                    <td>{{ coach.last_name }}</td>
                {% else %}
                    <td>--</td>
                {% endif %}
                <td>{{ coach.telegram_name }}</td>
                {% if coach.phone %}
                    <td>{{ coach.phone }}</td>
                {% else %}
                    <td>--</td>
                {% endif %}
                <td>{{ coach.started_to_work|date:"d M Y" }}</td>
                {% if coach.quantity %}
                    <td>{{ coach.quantity }}</td>
                {% else %}
                    <td>0</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/coaches/coach_update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Изменить данные о тренере: </h1>
     <form action="" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Изменить" %}
    </form>
{% endblock %}