source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


api_url = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include(api_url)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from webapp.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    ClientGroupUpdateView, ClientDeletedListView, ClientRestoreView,\
    PaymentCreateView,  PaymentUpdateView, PaymentDeleteView, \
    CoachListView, CoachDetailView, CoachCreateView, CoachUpdateView, CoachDeleteView, CoachStatisticsView,\
    GroupListView, GroupDetailView, GroupCreateView, GroupUpdateView, GroupDeleteView, \
    GroupClientUpdateView, GroupClientDeleteView, \
    TrainingListView, TrainingCreateView, TrainingDeleteView, \
    SendInvite, Mailing, GroupMailing


app_name = 'webapp'

client_url = [
    path('', ClientListView.as_view(), name='index'),
    path('deleted/list', ClientDeletedListView.as_view(), name='deleted_list'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('<int:pk>/client/restore', ClientRestoreView.as_view(), name='client_restore'),
    path('<int:pk>/client/update', ClientGroupUpdateView.as_view(), name='client_group_update'),
]

payment_url = [
    path('<int:pk>/create/', PaymentCreateView.as_view(), name='payment_create'),
    path('<int:pk>/update/', PaymentUpdateView.as_view(), name='payment_update'),
    path('<int:pk>/delete/', PaymentDeleteView.as_view(), name='payment_delete'),
]

coach_url = [
    path('list/', CoachListView.as_view(), name='coach_list'),
    path('<int:pk>/detail/', CoachDetailView.as_view(), name='coach_detail'),
    path('create/', CoachCreateView.as_view(), name='coach_create'),
    path('<int:pk>/update/', CoachUpdateView.as_view(), name='coach_update'),
    path('<int:pk>/delete/', CoachDeleteView.as_view(), name='coach_delete'),
    path('statistics/', CoachStatisticsView.as_view(), name='coach_statistics'),

]

group_url = [
    path('list/', GroupListView.as_view(), name='group_list'),
    path('<int:pk>/detail/', GroupDetailView.as_view(), name='group_detail'),
    path('create/', GroupCreateView.as_view(), name='group_create'),
    path('<int:pk>/update/', GroupUpdateView.as_view(), name='group_update'),
    path('<int:pk>/delete/', GroupDeleteView.as_view(), name='group_delete'),
    path('<int:pk>/client/update', GroupClientUpdateView.as_view(), name='group_client_update'),
    path('<int:pk>/client/delete', GroupClientDeleteView.as_view(), name='group_client_delete'),
]


training_url = [
    path('<int:pk>/list/', TrainingListView.as_view(), name='training_list'),
    path('<int:pk>/create/', TrainingCreateView.as_view(), name='training_create'),
    path('<int:pk>/delete/', TrainingDeleteView.as_view(), name='training_delete'),
]

send_invitee_massage_url = [
    path('<int:pk>/invite/', SendInvite.as_view(), name='send_invite'),
    path('<int:pk>/group/', GroupMailing.as_view(), name='send_group_mailing'),
    path('mailing/', Mailing.as_view(), name='mailing_page'),
]

urlpatterns = [
    path('', include(client_url)),
    path('client/', include(client_url)),
    path('payment/', include(payment_url)),
    path('coach/', include(coach_url)),
    path('group/', include(group_url)),
    path('training/', include(training_url)),
    path('send/', include(send_invitee_massage_url))
]

source/webapp/views/client_views.py
from django.core.exceptions import BadRequest
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.utils.http import urlencode
from django.urls import reverse, reverse_lazy
from django.db.models import Count, QuerySet
from webapp.models import Client
from webapp.forms import ClientForm, AddGroupClient, SearchForm
from webapp.filters import ClientFilter
from django.db.models import Q
from typing import Optional, Union


class ClientListView(ListView):
    model = Client
    template_name: str = 'clients/clients_list.html'
    context_object_name: str = 'clients'
    paginate_by: int = 10

    def get_search_form(self) -> SearchForm:
        return SearchForm(self.request.GET)

    def get_search_value(self) -> Optional[str]:
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get(self, request, *args, **kwargs) -> Union[redirect, ListView]:
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.filter(is_active=True).annotate(visit_count=Count('trainings'))
        if self.search_value:
            queryset = queryset.filter(
                Q(telegram_name__icontains=self.search_value) | Q(phone__icontains=self.search_value))
        return ClientFilter(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['filter'] = ClientFilter(self.request.GET, queryset=self.get_queryset())
        context['form'] = self.form
        if self.request.GET.get('is_paid'):
            context['query'] = urlencode({'is_paid': self.request.GET.get('is_paid')})
        elif self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ClientCreateView(CreateView):
    model = Client
    form_class: ClientForm = ClientForm
    template_name: str = 'clients/client_create.html'

    def get_success_url(self) -> str:
        return reverse('webapp:client_detail', kwargs={'pk': self.object.pk})


class ClientDetailView(DetailView):
    model = Client
    template_name: str = 'clients/client_detail.html'

    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.filter(is_active=True).annotate(visit_count=Count('trainings'))
        return queryset

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        client = self.get_object()
        payments = client.payments.order_by('-paid_at')
        paginator = Paginator(payments, 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        is_active = Client.objects.active_clients().filter(pk=client.pk)
        context['form'] = AddGroupClient() if is_active and client.group is None else None
        context['page_obj'] = page_obj
        context['is_paginated'] = page_obj.has_other_pages()
        context['payments'] = page_obj.object_list
        return context


class ClientUpdateView(UpdateView):
    template_name = 'clients/client_update.html'
    model = Client
    form_class = ClientForm

    def get_success_url(self) -> str:
        return reverse('webapp:client_detail', kwargs={'pk': self.object.pk})


class ClientDeleteView(DeleteView):
    template_name: str = 'clients/client_delete.html'
    model = Client
    context_object_name: str = 'client'
    success_url: str = reverse_lazy('webapp:index')

    def post(self, request, *args, **kwargs):
        client = get_object_or_404(Client, pk=int(kwargs.get('pk')))
        client.is_active = False
        client.group = None
        client.save()
        return redirect(self.success_url)


class ClientRestoreView(DeleteView):
    template_name: str = 'clients/client_restore.html'
    model = Client
    context_object_name: str = 'client'
    success_url: str = reverse_lazy('webapp:deleted_list')

    def post(self, request, *args, **kwargs):
        client = get_object_or_404(Client, pk=int(kwargs.get('pk')))
        client.is_active = True
        client.save()
        return redirect(self.success_url)


class ClientDeletedListView(ListView):
    model = Client
    template_name: str = 'clients/clients_deleted_list.html'
    context_object_name: str = 'clients'
    paginate_by: int = 10

    def get_search_form(self) -> SearchForm:
        return SearchForm(self.request.GET)

    def get_search_value(self) -> Optional[str]:
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get(self, request, *args, **kwargs) -> Union[redirect, ListView]:
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.filter(is_active=False).annotate(visit_count=Count('trainings'))
        if self.search_value:
            queryset = queryset.filter(
                Q(telegram_name__icontains=self.search_value) | Q(phone__icontains=self.search_value))
        return ClientFilter(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['filter'] = ClientFilter(self.request.GET, queryset=self.get_queryset())
        context['form'] = self.form
        if self.request.GET.get('is_paid'):
            context['query'] = urlencode({'is_paid': self.request.GET.get('is_paid')})
        elif self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ClientGroupUpdateView(View):
    def post(self, request, *args, **kwargs) -> HttpResponse:
        client_pk: int = kwargs.get('pk')
        group_id: int = int(request.POST.get('group_id'))
        is_active: bool = Client.objects.active_clients().filter(pk=client_pk)
        client: Client = get_object_or_404(Client, pk=client_pk)
        if is_active and client.group is None:
            client.group_id = group_id
            client.save()
            return redirect(self.get_redirect_url(group_id))
        raise BadRequest('Клиент неактивен или уже состоит в группе')

    def get_redirect_url(self, group_pk: int) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': group_pk})

source/webapp/views/coach_views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.db.models import Count, QuerySet
from webapp.models import Coach
from webapp.forms import CoachForm, CoachStatisticsPeriodForm


class CoachListView(ListView):
    model = Coach
    template_name: str = 'coaches/coach_list.html'
    context_object_name: str = 'coaches'
    paginate_by: int = 10


class CoachDetailView(DetailView):
    model = Coach
    template_name: str = 'coaches/coach_detail.html'
    context_object_name: str = 'coach'

    def get_context_data(self, **kwargs) -> dict:
        groups = self.get_object().groups.filter(is_active=True).all()
        return super().get_context_data(groups=groups, **kwargs)


class CoachCreateView(CreateView):
    model = Coach
    template_name: str = 'coaches/coach_create.html'
    form_class = CoachForm

    def get_success_url(self) -> str:
        return reverse('webapp:coach_detail', kwargs={'pk': self.object.pk})


class CoachUpdateView(UpdateView):
    model = Coach
    template_name: str = 'coaches/coach_update.html'
    form_class = CoachForm

    def get_success_url(self) -> str:
        return reverse('webapp:coach_detail', kwargs={'pk': self.object.pk})


class CoachDeleteView(DeleteView):
    model = Coach
    template_name: str = 'coaches/coach_delete.html'
    context_object_name: str = 'coach'
    success_url: str = reverse_lazy('webapp:coach_list')


class CoachStatisticsView(ListView):
    model = Coach
    template_name: str = 'coaches/coach_statistics.html'
    context_object_name: str = 'coaches'
    paginate_by: int = 10

    def get_queryset(self) -> QuerySet:
        start_date = self.request.GET.get('start_date')
        end_date = self.request.GET.get('end_date')
        coaches = super().get_queryset()
        if start_date and end_date:
            coaches = coaches.filter(
                    coach_trainings__created_at__gte=start_date, coach_trainings__created_at__lte=end_date
                )
        queryset = coaches.annotate(quantity=Count('coach_trainings')).order_by('telegram_name')
        return queryset

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['form'] = CoachStatisticsPeriodForm(self.request.GET)
        return context

source/webapp/views/groups_views.py
from django.http import HttpRequest
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, View
from webapp.models import Group, Client
from webapp.forms import GroupForm
from django.urls import reverse, reverse_lazy
from webapp.forms import AddClientGroup


class GroupListView(ListView):
    model = Group
    template_name: str = 'groups/group_list.html'
    context_object_name: str = 'groups'
    paginate_by: int = 5

    def get_queryset(self):
        return Group.objects.filter(is_active=True)


class GroupDetailView(DetailView):
    model = Group
    template_name: str = 'groups/group_detail.html'

    def get_context_data(self, **kwargs) -> dict:
        clients = self.get_object().clients.filter(is_active=True).all()
        clients_in_group = True if self.get_object().clients.active_clients().filter(is_active=True, group__isnull=True) else False
        form = AddClientGroup()
        return super().get_context_data(clients=clients, form=form, clients_in_group=clients_in_group, **kwargs)


class GroupCreateView(CreateView):
    model = Group
    form_class = GroupForm
    template_name: str = 'groups/group_create.html'

    def get_success_url(self) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': self.object.pk})


class GroupUpdateView(UpdateView):
    model = Group
    template_name: str = 'groups/group_update.html'
    form_class = GroupForm

    def get_success_url(self) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': self.object.pk})


class GroupDeleteView(DeleteView):
    model = Group
    template_name: str = 'groups/group_delete.html'
    context_object_name: str = 'group'
    success_url: str = reverse_lazy('webapp:group_list')

    def post(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=int(kwargs.get('pk')))
        group.is_active = False
        clients = Client.objects.all().filter(group__id=group.pk)
        for client in clients:
            client.group = None
            client.save()

        group.save()
        return redirect(self.success_url)


class GroupClientUpdateView(View):
    def post(self, request, *args, **kwargs):
        group_pk = kwargs.get('pk')
        client_ids = request.POST.getlist('active_client_id')
        for client_id in client_ids:
            client = get_object_or_404(Client, pk=int(client_id))
            client.group_id = group_pk
            client.save()
        return redirect(self.get_redirect_url(group_pk))

    def get_redirect_url(self, group_pk: int) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': group_pk})


class GroupClientDeleteView(View):
    def get(self, request: HttpRequest, *args: tuple, **kwargs: dict):
        client_id = kwargs.get('pk')
        client = get_object_or_404(Client, pk=client_id)
        group_pk = client.group_id
        client.group_id = None
        client.save()
        return redirect(self.get_redirect_url(group_pk))

    def get_redirect_url(self, group_pk) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': group_pk})

source/webapp/views/trainings_views.py
from django.http import HttpRequest
from django.views.generic import DetailView, View, DeleteView
from webapp.models import Training, Client
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic.list import MultipleObjectMixin


class TrainingListView(DetailView, MultipleObjectMixin):
    model = Client
    template_name: str = 'trainings/training_list.html'
    paginate_by: int = 8

    def get_context_data(self, **kwargs) -> dict:
        client = get_object_or_404(Client, pk=self.kwargs.get('pk'))
        object_list = client.trainings.all()
        context = super(TrainingListView, self).get_context_data(object_list=object_list)
        return context


class TrainingCreateView(View):
    def post(self, request: HttpRequest, *args: tuple, **kwargs: dict):
        client = get_object_or_404(Client, pk=self.kwargs.get('pk'))
        if client in Client.objects.active_clients():
            training = Training.objects.create(client=client, group=client.group)
            training.save()
        return redirect('webapp:client_detail', client.pk)


class TrainingDeleteView(DeleteView):
    model = Training
    template_name: str = 'trainings/training_delete.html'
    context_object_name: str = 'training'

    def get_success_url(self) -> str:
        return reverse('webapp:training_list', kwargs={'pk': self.object.client.pk})

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">


<!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body id="body-pd">

<div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar" class="active">
            {% block sidenav %}
            <ul class="list-unstyled components">
                <li>
                    <a href="#clientSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        Клиенты
                    </a>
                    <ul class="collapse list-unstyled" id="clientSubmenu">
                        <li>
                            <a href="{% url 'webapp:index' %}">
                                <i class="bi bi-person-lines-fill"></i>
                                Список клиентов
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'webapp:mailing_page' %}">
                                <i class='bi bi-envelope nav_icon'></i>
                                Рассылка
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'webapp:client_create' %}">
                                <i class="bi bi-plus-circle"></i>
                                Добавить клиента
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'webapp:deleted_list' %}">
                                <i class="bi bi-trash"></i>
                                Удаленные клиенты
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#groupSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        Группы
                    </a>
                    <ul class="collapse list-unstyled" id="groupSubmenu">
                        <li>
                            <a href="{% url 'webapp:group_list' %}">
                                <i class="bi bi-collection"></i>
                                Список групп
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'webapp:group_create' %}">
                                <i class="bi bi-plus-circle"></i>
                                Добавить группу
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#coachSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        Тренера
                    </a>
                    <ul class="collapse list-unstyled" id="coachSubmenu">
                        <li>
                            <a href="{% url 'webapp:coach_list' %}">
                                <i class="bi bi-person-lines-fill"></i>
                                Список тренеров
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'webapp:coach_create' %}">
                                <i class="bi bi-plus-circle"></i>
                                Добавить тренера
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'webapp:coach_statistics' %}">
                                <i class="bi bi-bar-chart"></i>
                                Статистика тренеров
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            {% endblock %}
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav id="topbar" class="navbar navbar-expand-lg navbar-light bg-light  d-flex align-items-center">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="nav_btn mr-3">
                        <i class="bi bi-list"></i>
                        Меню
                    </button>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse ms-auto" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100">
                      <li class="nav-item">
                          <a href="{% url 'webapp:index' %}" class="nav_btn my-2">Главная</a>
                      </li>

                  {% block topbar %}{% endblock %}{% if request.user.is_authenticated %}
                      <li class="nav-item ml-lg-auto order-lg-2">
                          <a class="nav_btn my-2" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">
                              Выйти
                          </a>
                      </li>

                {% else %}
                      <li class="nav-item ml-lg-auto order-lg-2">
                          <a class="nav_btn my-2" href="{% url 'accounts:login' %}?next={% if request.GET.next %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">
                              Войти
                          </a>
                      </li>

                {% endif %}
                  </ul>
                </div>


                </div>
            </nav>

            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
<script src="{% static 'js/style.js' %}"></script>
</body>
</html>